### ISSUE TITLE
Velg CSS rammeverk

### ISSUE THREAD

**Issue by simendag** [Log234/Mandater#12]
Det må tas en avgjørelse på hvilk(e)t CSS rammeverk som skal brukes.

**Comment by simendag** [comment]
Det virker som om [flexbox](https://www.w3.org/TR/css-flexbox-1/) er fremtiden, vil anbefale å se på det før man starter å bruke klasser og snodige ting fra rammeverk som man egentlig ikke trenger etterhvert (posisjonering osv kan håndteres av flexbox, og alt annet av rammeverke(ne) eventuelt?). Du som er glad i detaljer kan trolig bli glad i [Basscss](http://basscss.com) eller [Tachyons](http://tachyons.io). Det skal nevnes at selv Bootstrap er ganske lite så lenge man gzipper, så det er ikke noen krise om vi ender opp med det fordi det er lett(ere). 

tl;dr: Flexbox burde helst brukes uansett. Basscss er veldig lite, Tachyons er mer en mellomting mellom Basscss og Bootstrap.

**Comment by Log234** [comment]
Bootstrap will do for now, we can revisit this issue in v1.1.0
