### ISSUE TITLE
Digitalisere whiteboard sketchen av første GUI konsept.

### ISSUE THREAD

**Issue by Log234** [Log234/Mandater#2]
Lage en sketch i photoshop/paint/e.l. for å gjøre videre diskusjon om idèen enklere.

- Legge til referanser for de forskjellige områdene, tall/bokstaver
- Kanskje lage en annen versjon med forslag for mobil kompabilitet.

**Comment by Edvarda-E** [comment]
De lyseblå og mørkeblå grafene burde ligge inntil hverandre, ettersom de er representanter for samme parti (parvis). Det burde vel også legges til tekst på grafen så det kommer frem hva den representerer. :)

Utover det har jeg bare småpirk som vi kan ta etterhvert.
