### ISSUE TITLE
Bibliotek for visualisering av data

### ISSUE THREAD

**Issue by Log234** [Log234/Mandater#24]
- Sjekke mulighet for Norgeskart-graf-visualisering

**Comment by simendag** [comment]
D3 støtter kart, det er en av grunnene til at jeg anbefaler det over de mer "enkle" bibliotekene

**Comment by simendag** [comment]
![example](https://user-images.githubusercontent.com/8669774/35778868-b6edda82-09c4-11e8-846e-a465fb99660e.png)
![example2](https://user-images.githubusercontent.com/8669774/35778869-bb05e31c-09c4-11e8-8080-121e2b1c2ede.png)
