### ISSUE TITLE
GUI Implement the second table

### ISSUE THREAD

**Issue by Log234** [Log234/Mandater#26]
Implement [Table 1](https://drive.google.com/open?id=1exqHVtfcM-1FahVVrcR7W5xNMCCtHvP_) that should receive data from states.

The result should be updated when the user makes changes to the parameters. #27 #48  
The Sainte-Laguë method needs to be implemented for the update to be calculated #28

**Comment by Log234** [comment]
Made superfluous by #48 and #28

**Comment by Edvarda-E** [comment]
I disagree that this is superfluous as the table has not been implemented yet. Updated issue name and description so it is more descriptive
