### ISSUE TITLE
Fix problems with new initialization in deployment

### ISSUE THREAD

**Issue by simendag** [Log234/Mandater#66]
New initialization works well locally, but does not work deployed to testing server -- presumably due to pathing problems in the new initialization. Needs fixing.

**Comment by simendag** [comment]
Update: I now believe the Azure server, like my own development environment, had too many folders (left-over before the renaming of ParliamentaryElections to PE). @Log234 can investigate this on Azure and fix it by deleting the extraneous folder.

**Comment by Log234** [comment]
Fixed by deleting the extra folders on the servers and restarting it.
