### ISSUE TITLE
Bestem hvilket DBHS som skal brukes

### ISSUE THREAD

**Issue by simendag** [Log234/Mandater#8]
Vi må velge et DBHS!

**Comment by Log234** [comment]
https://docs.microsoft.com/en-us/ef/core/providers/in-memory/

Tanker?

**Comment by simendag** [comment]
Nja, kanskje noe mer robust enn det. Har brukt det før, men det er jo ikke ment for produksjonsmiljøer akkurat.

**Comment by Log234** [comment]
Evt har vi SQLite, det kan også kjøres i minnet.

**Comment by Log234** [comment]
Vet du... Vi kan jo nesten gå med MongoDB, ettersom vi bare trenger å levere datasett uansett.

**Comment by Log234** [comment]
Et godt alternativ kan være: https://github.com/apache/ignite

**Comment by Log234** [comment]
Tester Apache Ignite, ser lovende ut.
Har både .Net og EntityFramework støtte.

**Comment by Log234** [comment]
Microsoft SQL Server?

**Comment by simendag** [comment]
Landet vel på InMemory for nå, da det er snakk om veldig lite data som alle finnes på fil for øyeblikket. Kan revurdere neste leveranse.
