### ISSUE TITLE
Velge graf-bibliotek

### ISSUE THREAD

**Issue by Log234** [Log234/Mandater#9]

**Comment by simendag** [comment]
https://github.com/react-d3-library/react-d3-library

d3.js har masse eksempler og kule ting på nett, og man vil trolig kunne konvertere disse til komponenter for lett arbeid i React, virker fornuftig.

Highcharts er kult men er proprietært.

De andre tror jeg mangler for mye til at det er vits i å bruke dem om vi vil ha mange forskjellige bra visualiseringer i samme stil.

**Comment by Log234** [comment]
Du har min stemme for d3.
